FROM golang:latest as BUILD

ENV GO111MODULE=on

WORKDIR /testdir

COPY . .

ENTRYPOINT ["go", "test", "-v", "./tests/...", "-coverpkg", "./my-ecommerce/...", "-cover", "-coverprofile", "coverage.out"]