version: "3"

services:
  discount-service:
    image: hashorg/hash-mock-discount-service
    container_name: discount-service
    ports:
    - 50051:50051
    networks:
      - app-network
  checkout-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: checkout-service
    ports:
    - 4513:4513
    networks:
      - app-network
    links:
      - discount-service
    depends_on:
      - discount-service

networks:
  app-network:
    driver: bridge