version: "3"

services:
  discount-service:
    image: hashorg/hash-mock-discount-service
    container_name: discount-service
    ports:
    - 50051:50051
    networks:
      - app-network
  checkout-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: checkout-service
    networks:
      - app-network
    links:
      - discount-service
    depends_on:
      - discount-service
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - checkout-service
    ports:
      - "4000:4000"
    networks:
      - app-network


networks:
  app-network:
    driver: bridge